sudo: required
services:
  - docker 
before_install:
  - docker build -t hdeudorb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hdeudorb/react-test npm test

after_success:
  - docker build -t hdeudorb/multi-client ./client
  - docker build -t hdeudorb/multi-nginx ./nginx
  - docker build -t hdeudorb/multi-server ./server
  - docker build -t hdeudorb/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tale those images and push them to docker hub
  - docker push hdeudorb/multi-client
  - docker push hdeudorb/multi-nginx
  - docker push hdeudorb/multi-server
  - docker push hdeudorb/multi-worker