version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr5/app/node_modules
      - ./server:/usr5/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
        - /usr5/app/node_modules
        - ./client:/usr5/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr5/app/node_modules
      - ./worker:/usr5/app
  nginx:
    restart: always
    build:
        dockerfile: Dockerfile.dev
        context: ./nginx
    ports:
        - '3050:80'  